[libraries]
assertj-bom = 'org.assertj:assertj-bom:3.26.3'
hamcrest = 'org.hamcrest:hamcrest:3.0'
jackson-bom = 'com.fasterxml.jackson:jackson-bom:2.18.0'
jakarta-servlet = 'jakarta.servlet:jakarta.servlet-api:6.0.0'
junit-bom = 'org.junit:junit-bom:5.11.2'
jsonassert = 'org.skyscreamer:jsonassert:1.5.3'
mockito-bom = 'org.mockito:mockito-bom:5.14.2'
spring-framework-bom = 'org.springframework:spring-framework-bom:6.1.13'
spring-security-bom = 'org.springframework.security:spring-security-bom:6.4.0-SNAPSHOT'
webauthn4j-core = 'com.webauthn4j:webauthn4j-core:0.26.0.RELEASE'

[plugins]
org-springframework-boot = 'org.springframework.boot:3.3.4'
io-spring-dependency-management = 'io.spring.dependency-management:1.1.6'
